
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3
    steps:
      -checkout
  
  server:
     docker:
        - image: circleci/node:10.15.3
     steps:
        - run: cd back-end && npm run dev
workflows:
    testing:
      - build 
      - server:
          requires:
            -build
      
  



#     steps:
#       - checkout

#       # todo: find nicer solution than constantly "cd"ing to unit_testing
#       - run: cd back-end && npm install
#       - run: cd front-end && npm install
#       - run: 
#           command: cd back-end && npm run dev
#           background: true 
#       - run: cd front-end && npm run start


      # TODO: add caching to speed things up.



# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           name: starting server
#           working_directory: back-end
#           start: npm run dev
#           wait-on: 'http://localhost:4000'

#       - cypress/run:
#           name: starting tests
#           working_directory: front-end
#           start: npm run start
#           wait-on: 'http://localhost:3000'
#           command: npm run cypress:open
