version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

    steps:
      - checkout

      # todo: find nicer solution than constantly "cd"ing to unit_testing
      - run: cd back-end && npm install
      - run: cd front-end && npm install
      - run: 
          command: cd back-end && npm run dev
          background: true 
      - run: cd front-end && node_modules/.bin/cypress open


      # TODO: add caching to speed things up.